### ISSUE TITLE
Inbox fetch fails

### ISSUE THREAD

**Issue by pkliang** [BatchLabs/Batch-Android-SDK#18]
Hi, we recently encountered a bug in the notification inbox of our Android app. The inbox fetcher always returns an exception with the following information when, for example, `fetchNewNotifications`  is called:

`The server was unable to complete your request in time. Please try again later. `

We also see an exception in the Batch internal log:
```
InboxFetchWebserviceClient - Failed to parse notification content, skipping.
com.batch.android.q.k: Missing key or invalid value type in response JSON.

Caused by: com.batch.android.json.JSONException: Value {"t":"c","l":"","i":","od":{"n":"","ct": "","ak":"","di":""},"r":{"m":1,"dmi":60,"dma":3600}} at com.batch of type java.lang.String cannot be converted to JSONObject
```
https://github.com/BatchLabs/Batch-Android-SDK/blob/a5468fb7f86c42a10363595b3293bccc27f83a68/Sources/sdk/src/main/java/com/batch/android/inbox/InboxFetchWebserviceClient.java#L133

We tested with different versions like 1.19.x or 1.20.x and saw the same exception.

Do you have any idea how to fix this bug? Thanks in advance.

**Comment by pkliang** [comment]
I believe this bug is related to 

https://github.com/BatchLabs/Batch-Android-SDK/blob/a5468fb7f86c42a10363595b3293bccc27f83a68/Sources/sdk/src/main/java/com/batch/android/inbox/InboxFetchWebserviceClient.java#L154

**Comment by arnaud-roland** [comment]
Hi,
Thank you for your report. This is actually a server-side issue related to our recent FCM API v1 support.
This should be fixed soon.

**Comment by arnaud-roland** [comment]
Hi, Thanks again for the report.
I'm closing this since the issue has been fixed.
