### ISSUE TITLE
The SDK does not handle the deeplinks associated with a campaign in some cases.

### ISSUE THREAD

**Issue by gilbertdigio** [BatchLabs/Batch-Android-SDK#20]
Hi,  we have problems with some users that after opening a push sent from the batch dashboard is not directed to the target screen. simply the app opens but does not redirect to the target. 

Our development and QA teams have tested with exactly the same campaign and with exactly the same deeplink and app opens on the target screen without any problems.

We have debugged the problem together with an affected user and what seems to happen is that the deeplink is not managed and propagated by the batch SDK. 

The activity that is associated in the manifest to manage the deeplinks is not invoked, so the onNewIntent() method is not invoked either.

## Reproduction steps
1. Send a campaign from the batch console with a deeplink pointing to the app schema.
2. Click on the push notification that is generated in the device.
3. The application opens but does not direct to the deeplink target instead it remains on the home screen.

NOTE: Only occurs with some users in this condition, Our team is not able to reproduce it.

Any idea why the SDK is ignoring the deeplink associated with the campaign in these cases?

Thanks in advance.

### SDK Version
v2.0.3
### Installation method
Google Play

**Comment by arnaud-roland** [comment]
Hi, thanks for the report, but to effectively investigate, we require more detailed information about the problem you're experiencing.

We recommend contacting our support team via live chat for real-time assistance. Alternatively, you can consult our [technical documentation](https://doc.batch.com/android/sdk-integration/) to ensure the SDK is correctly integrated into your project. 

Have a nice day,
